#!/bin/bash

# enable shell script debugging
# set -x

# display help if incorrect usage or on --help
if [[ ($# == 0) || ($1 == "--help") ]]
then
    printf "Usage\n\tspot <spotify web url OR search string>\n\tspot --help to see this help text\n"
    printf "\nExamples\n\tspot http://open.spotify.com/user/1248318865/playlist/7uKPSEwUQzx3c9EU032lU6\n"
    printf "\tspot breaking benjamin\n"
    printf "\tspot --help\n"
    exit 0
fi

# meat of the script
# use apple script to put a string in spotify app search box
_runSpotOsaScript() {
    osascript<<EOF
tell application "spotify" to activate
delay 0.5
tell application "System Events"
  keystroke "l" using command down
  keystroke "a" using command down
  keystroke ascii character 8
  delay 0.2
  keystroke "$*"
  keystroke return
end tell
EOF
    exit 0
}

# matches input string against keyword
_matches() {
    declare -r input="$1"
    declare -r pattern="$2"
    echo "$input" | grep -qE "$pattern"
}

# open url in spotify
_openInSpotify() {
    declare -r url=$1
    IFS='\?' read -r -a filterQueryParams <<< "$url"
    IFS='\/' read -r -a urlComponents <<< "${filterQueryParams[@]:0:1}"
    _runSpotOsaScript spotify:`tr " " ":" <<< ${urlComponents[@]:3}`
}

# search for input string in spotify app
_searchInSpotify() {
    _runSpotOsaScript $@
}

# if input is a url open it in spotify app. If not, search for input in spotify
if _matches $1 "^http[s]?://.*\.spotify\..*"
then
    _openInSpotify $1
else
    _searchInSpotify "$*"
fi
